FROM python:3.11-bookworm

WORKDIR /app

COPY ../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ../backend /app/backend

CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]