FROM python:3.11

WORKDIR /app

COPY ./etl /app/etl
COPY ../backend /app/backend
COPY ../requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "etl/run_etl.py", "--date", "2025-05-07"]
